config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :users
  root 'locations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  belongs_to :location

  def self.create_forecasts(location_id)
    location = Location.find(location_id)
    weather_service = WeatherService.new(location.latitude(location.ip_address), location.longitude(location.ip_address))
    forecast_data = weather_service.parse_forecast()

    forecast_data[:forecast].each do |day|
      location.forecasts.create(date: Date.parse(day[:date]), high_temperature: day[:high], low_temperature: day[:low])
    end
  end

end

app/models/location.rb
# Location Model

class Location < ApplicationRecord
  validates :text_address, presence: false
  validates :ip_address, presence: true

  has_many :forecasts, dependent: :destroy

  def current_forecast(ip)
    weather_service = WeatherService.new(latitude(ip), longitude(ip))
    # weather_service.forecast
    # weather_service.parse_forecast(weather_service.forecast)
    weather_service.parse_forecast()

  end

  def latitude(ip)
    ip_info_service = IpInfoService.new(ip)
    ip_info = ip_info_service.info
    ip_info[:latitude]
  end

  def longitude(ip)
    ip_info_service = IpInfoService.new(ip)
    ip_info = ip_info_service.info
    ip_info[:longitude]
  end

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, world!"
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # Find where I save text_address, to also save ip_address

  # GET /locations/1 or /locations/1.json
  def show
    @location = Location.find(params[:id])
    @forecasts = @location.forecasts
  end

  # GET /locations/new
  def new
    @location = Location.new
    # @forecast = @location.current_forecast(ip = request.headers['X-Forwarded-For'].split(',').first.strip)
    # @address = @location.text_address
    # @location.ip_address = request.headers['X-Forwarded-For'].split(',').first.strip if request.headers['X-Forwarded-For']
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    # TODO find out where is location_params coming from. I need to create a location object with IP address as well
    @location = Location.new(location_params)
    # @location.ip_address = request.remote_ip
    @location.ip_address = request.headers['X-Forwarded-For'].split(',').first.strip if request.headers['X-Forwarded-For']


    respond_to do |format|
      if @location.save
        Forecast.create_forecasts(@location.id)
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:ip_address, :text_address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text_address, style: "display: block" %>
    <%= form.text_field :text_address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Ip address:</strong>
    <%= location.ip_address %>
  </p>

  <p>
    <strong>Text address:</strong>
    <%= location.text_address %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to "Show this location", location %>
    </p>
  <% end %>
</div>

<%= link_to "New location", new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>


<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <% if @forecasts.any? %>
  <div>
    <div>
      <h1>Weather Forecast For This Location</h1>
        <ul>
          <% @forecasts.each do |forecast| %>
            <li>
              Date: <%= forecast.date %>,
              High: <%= forecast.high_temperature %>°F,
              Low: <%= forecast.low_temperature %>°F
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No forecast data available for this location.</p>
      <% end %>
    </div>

    <div>
      <h1>Temperature Forecast Graph</h1>
      <% dates = @forecasts.map { |forecast| forecast.date.to_s } %>
      <% high_temps = @forecasts.map { |forecast| forecast.high_temperature } %>
      <% low_temps = @forecasts.map { |forecast| forecast.low_temperature } %>
      <%= image_tag "https://image-charts.com/chart?cht=lc&chs=800x400&chd=t:#{high_temps.join(',')}|#{low_temps.join(',')}&chxt=x,y&chxl=0:|#{dates.join('|')}&chdl=High+Temperature|Low+Temperature&chco=FF0000,0000FF", alt: "Temperature Chart" %>
    </div>

</div>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>